image: gitpod/workspace-full

tasks:
  - command: >
      mkdir /workspace/wiremock/
      wget -P /workspace/wiremock/ "http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.25.0/wiremock-standalone-2.25.0.jar"
      java -jar wiremock-standalone-2.25.0.jar --root-dir /workspace/springboottest/wiremock --port 60600
    
ports:
  - port: 60600
    onOpen: ignore